data:
  root_dir: ./Simulator/results/2026_04_08_14_23_16/simulated_hologram/holo_0.tiff
optim:
  algo: Adam
  params:
    lr: 0.0005
    eps: 1.0e-07
    betas:
    - 0.9
    - 0.95
  lr_physics: 0.005
nepochs: 20000
model:
  class: HoloSolver
  regularization:
    with_bc: true
    with_sparsity: false
    sparsity_weight: 2.0e-05
    with_tv: false
    tv_weight: 0.0005
  physical_params:
    phase_shift: 0.0714
    physicalLength: 0.1375
    step_z: 0.5
    waveLength: 0.66
    z_max: 50.0
  nerf_params:
    model: MorpHoloNet
    gaussian_proj: 64
    gaussian_scale: 10
  vram_params:
    activ: false
    chunk_size: 15000000
    checkpoint: false
  pre_training:
    activ: true
    epochs: 1500
    targets:
    - x0: 111.0
      y0: 97.0
      z0: 43.5
      r: 6.74
    - x0: 60.0
      y0: 55.0
      z0: 13.5
      r: 6.74
test:
  save_dir: ./Results
  weights_path: ./logs/HoloSolver_70/best_model.pt
logging:
  logdir: ./logs
