data:
  root_dir: ./Simulator/results/2026_04_06_01_57_41/simulated_hologram/holo_0.tiff
optim:
  algo: Adam
  params:
    lr: 0.0005
    eps: 1.0e-07
    betas:
    - 0.9
    - 0.95
  lr_physics: 0.005
nepochs: 20000
model:
  class: HoloSolver
  regularization:
    with_bc: true
    with_sparsity: false
    sparsity_weight: 2.0e-05
    with_tv: false
    tv_weight: 0.0005
  physical_params:
    phase_shift: 0.0714
    physicalLength: 0.1375
    step_z: 0.5
    waveLength: 0.66
    z_max: 50.0
  nerf_params:
    model: MorpHoloNet
    gaussian_proj: 64
    gaussian_scale: 10
  vram_params:
    activ: false
    chunk_size: 10000000
    checkpoint: false
  pre_training:
    activ: true
    epochs: 300
    targets:
    - x0: 216.0
      y0: 464.0
      z0: 30.0
      r: 5.58
    - x0: 133.0
      y0: 195.0
      z0: 44.0
      r: 7.06
    - x0: 110.0
      y0: 274.0
      z0: 16.5
      r: 4.78
    - x0: 86.0
      y0: 505.0
      z0: 30.5
      r: 3.68
    - x0: 64.0
      y0: 47.0
      z0: 48.0
      r: 3.93
test:
  save_dir: ./Results
  weights_path: ./logs/HoloSolver_70/best_model.pt
logging:
  logdir: ./logs
