data:
  root_dir: ./Simulator/results/2026_03_04_15_17_44/simulated_hologram/holo0.tiff
optim:
  algo: Adam
  params:
    lr: 0.0001
nepochs: 5000
model:
  class: HoloSolver
  regularization:
    with_bc: true
    with_sparsity: true
    sparsity_weight: 0.05
    with_tv: true
    tv_weight: 0.01
  physical_params:
    phase_shift: 0.005
    physicalLength: 0.25
    step_z: 0.5
    waveLength: 0.66
    z_max: 100.0
  nerf_params:
    model: MorpHoloNet
    gaussian_proj: 64
    gaussian_scale: 7
test:
  save_dir: ./holotrack_model/Results/2026_03_04_15_17_44
  weights_path: ./logs/HoloSolver_39/best_model.pt
logging:
  logdir: ./holotrack_model/Logs/2026_03_04_15_17_44
