data:
  root_dir: ./holotrack_model/holograms/Hypotonic_RBC.tif
  blurring:
    activ: false
    blur_epochs: 2000
    max_sigma: 1.0
    min_sigma: 0.1
    kernel_size: 9
optim:
  algo: Adam
  params:
    lr: 0.0005
    eps: 1.0e-07
    betas:
    - 0.9
    - 0.95
  lr_physics: 0.005
  scheduler:
    activ: false
    milestones:
    - 3000
    gamma: 0.1
    warm_start: false
  stop_criteria:
    activ: false
    patience: 3
    interval: 200
    delta: 0.0001
nepochs: 20000
model:
  class: HoloSolver
  regularization:
    with_bc: true
    with_sparsity: false
    sparsity_weight: 2.0e-05
    with_tv: false
    tv_weight: 0.0005
  physical_params:
    phase_shift: 0.437
    physicalLength: 0.5
    step_z: 1.0
    waveLength: 0.399
    z_max: 100.0
  nerf_params:
    model: MorpHoloNet
    gaussian_proj: 64
    gaussian_scale: 8.0
    barf: false
    barf_epochs: 1000
  vram_params:
    activ: False
    chunk_size: 10000000
    checkpoint: False
  pre_training:
    activ: True
    epochs: 1500
    targets:
    - x0: 64.0
      y0: 64.0
      z0: 44.0
      r: 3.0
test:
  save_dir: ./Results
  weights_path: ./logs/HoloSolver_70/best_model.pt
logging:
  logdir: ./logs
