data:
  root_dir: ../holograms/E_coli.tif

optim:
  algo: Adam
  params:
    lr: 0.0001 # learning rate: 0.00001~0.0001

nepochs: 5000
model:
  class: "HoloSolver"

  regularization:
    with_bc: True
    with_sparsity: True
    sparsity_weight: 0.05
    with_tv: True
    tv_weight: 0.01
  
  physical_params:
    phase_shift: 0.335
    physicalLength: 0.25
    step_z: 0.5
    waveLength: 0.3991
    z_max: 30

  #nerf_params:
  #  model: "Hash_Grid"

  nerf_params:
    model: "MorpHoloNet"
    gaussian_proj: 64
    gaussian_scale: 7

test:
  save_dir: "../Results"
  weights_path: "./logs/HoloSolver_39/best_model.pt"

logging:
  # wandb: 
  #   project: sample_project
  #   entity: sample_entity
  logdir: "./logs"  # Better to provide the fullpath, especially on the cluster
